### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/d#6]
In order to launch we should:
- [x] Turn on Travis CI for the track (kytrinyx)
- [x] Add D as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/tracks) (kytrinyx)
- [x] Implement at least 10 problems
- [x] Write documentation (see below)
- [ ] Find a person or (ideally) a handful of people willing to check exercism regularly (daily?) to review solutions
- [x] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in D whether or not you've submitted the problem to the site. The first track mentor needs to be added manually by kytrinyx, but after that there's a section in the account where existing track mentors can invite new ones.
- [x] Add a language icon or logo (see below) + attribution (in README)
- [x] Toggle `"active"` to `true` in `config.json`
- [ ] Mention it in the next "Behind the Scenes" newsletter (kytrinyx)
## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:
- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:
- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.
## Logo/Icon

We try to create a language icon that has the exercism colors, and is recognizably similar to the language icon. Sometimes this isn't possible due to copyright issues. See http://exercism.io/languages for all the existing icons.

We're in the process of moving each individual language track icon into the specific language track repository. Putting all the language-specific stuff together makes it easier to manage. In the meanwhile, we need to have everything in two places.

If image assets are not your strong suit, just find a reasonable image to start from, along with the information about the licensing, and we'll figure out the colorization thing (I've written some scripts to help me do this part).

Some icons are the official language logo (tweaked). Where a language doesn't seem to have an official logo, or where the official logo has copyright issues, we just make something up.

**exercism.io**

The logo should be named `dlang.png` and live in `/public/img/tracks/` in the exercism/exercism.io repository.
https://github.com/exercism/exercism.io/tree/master/public/img/tracks

Attribution goes in https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md

**xdlang**

The logo should be named `icon.png` and live under `img/` in this repository. If you know how, go ahead and make an SVG as well.

Attribution goes in the README.md file.
## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:
- Each submission receives feedback quickly, preferably within the first 24 hours.
- The code reviews do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore aspects of the language. Referencing existing blog posts and style guides seems to work well, when making specific recommendations.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by kytrinyx** [comment]
I've added both @tmccombs and @celavek as track mentors for D on the site, meaning that if you log in and go to the Activity Stream, you'll see all the D solutions that get submitted. (And of course—no pressure!)

**Comment by celavek** [comment]
I made an announcement on the dlang.org that the track is alive. We'll see how that goes.
I hope it gets some traction and maybe some more seasoned D programmers contributing 
exercises and reviews.

**Comment by celavek** [comment]
And thank tou for the mentor statis of course 😃

**Comment by kytrinyx** [comment]
If you see others who should have mentor status on the track you can invite them on your exercism account page.

**Comment by kytrinyx** [comment]
This track is active. Closing.
